[general]
documents_per_page = 20

[logging]
filename = "application.log"
level = "debug"

[session]
ttl = "90 00:00:00" # 90 days
cookie = "_tangomike_session_id"

[database]
uri = "mongodb://db:27017/tangomike"
timeout = 1.1 # 1.1 seconds

[queue]
type = "mongo"

[mongo_queue]
tasks_collection = "tangomike_tasks"
keep_done_tasks_for = "90 00:00:00" # 90 days
cleanup_interval = "01:00:00" # 1 hour

[cache]
level1 = "request_local"
level2 = "simple"

# [memcached]
# backends = ["127.0.0.1:11211"]